# Generated by Django 3.2.16 on 2023-01-30 17:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber_export', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('email', models.CharField(max_length=200)),
                ('ck_api', models.CharField(max_length=200)),
                ('ck_secret', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagid',
            field=models.IntegerField(unique=True),
        ),
    ]
