# Generated by Django 3.2.16 on 2023-01-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber_export', '0002_auto_20230130_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='id',
        ),
        migrations.AlterField(
            model_name='api',
            name='email',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
