# Generated by Django 3.2.16 on 2023-02-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber_export', '0005_auto_20230205_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
