# Generated by Django 3.2.16 on 2023-02-11 20:05

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber_export', '0006_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ck_api',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ck_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
